on:
  push:
    branches: [master]

name: "Transifex synchronization"

jobs:
  upload-to-transifex:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v3   
      
      - name: Upload
        env:
          TRANSIFEX_PASSWORD: ${{ secrets.TX_TOKEN }}
        run: |
            if [ ! -z "$TRANSIFEX_PASSWORD" ]; then
              pip install --user virtualenv
              virtualenv ~/env
              source ~/env/bin/activate
              pip install transifex-client
              echo -e "[https://www.transifex.com]\nhostname = https://www.transifex.com\nusername = api\npassword = ${TRANSIFEX_PASSWORD}\n" > ~/.transifexrc
              tx push -s --no-interactive
            fi